spring:
  profiles:
    active: local
  batch:
    job:
      names: ${jobs.name:NONE}


---

spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver


---

spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/ghsong
      username: ghsong
      password: 1646
      driver-class-name: org.mariadb.jdbc.Driver
